# Generated by Django 3.1.2 on 2020-11-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancellation',
            old_name='user',
            new_name='participant',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Coffee Mug', 'Coffee Mug'), ('Stickers', 'Sticker'), ('Backpack', 'Backpack')], max_length=200),
        ),
    ]
