# Generated by Django 3.1.2 on 2020-11-11 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_auto_20201111_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.organiser'),
        ),
    ]
