# Generated by Django 3.1.2 on 2020-11-12 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_event_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='organiser',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.organiser'),
        ),
    ]
