# Generated by Django 3.1.2 on 2020-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_item_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='about',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
